# 예: .github/workflows/docker-deploy.yml
name: CI/CD Pipeline - Docker Build and Deploy

on:
  push:
    branches:
      - master  # master 브랜치에 push 될 때마다 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest

      - name: SSH and deploy on GCP server
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          access_token_lifetime: 500s
  
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
  
      - name: Use gcloud CLI
        run: gcloud info

      - name: Copy files to GCE
        run: |
          gcloud compute scp \
          docker-compose.yml \
          ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_INSTANCE_NAME }}:${{ secrets.GCP_DOCKER_COMPOSE_PATH }}/docker-compose.yml \
          --zone ${{ secrets.GCP_INSTANCE_ZONE }}

      - name: Deploy to GCE
        run: |
          gcloud compute ssh ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_INSTANCE_NAME }} \
          --zone ${{ secrets.GCP_INSTANCE_ZONE }} \
          --command "\
            cd ${{ secrets.GCP_DOCKER_COMPOSE_PATH }} && \
            sudo docker compose -f docker-compose.yml pull ${{ secrets.DOCKER_IMAGE_NAME }} && \
            sudo docker compose -f docker-compose.yml up -d ${{ secrets.DOCKER_IMAGE_NAME }}"

